const productos = [
    { nombre: "Auriculares in-ear inalambricos", 
    color: "Negro", 
    precio: "5000", 
    stock: "3", 
    id: 1, 
    marca: "XIAOMI", 
    imagen: "./multimedia/auricularesp.webp" },

    { nombre: "Auriculares in-ear QCY T1C inalambricos ",
     color: "Blanco", 
     precio: "8000", 
     stock: "2", 
     id: 2, 
     marca: "XIAOMI", 
     imagen: "./multimedia/aurisblancos.webp" },

    { nombre: "Auriculares in-ear inalambricos Redmi Airdots", 
    color: "Negro", 
    precio: "7000", 
    stock: "1", 
    id: 3, 
    marca: "XIAOMI", 
    imagen: "./multimedia/aurisinear.webp" },

    { nombre: "Auriculares in-ear inalambricos Redmi Airdots 3", 
    color: "Azul", 
    precio: "5500", 
    stock: "4", 
    id: 4, 
    marca: "XIAOMI", 
    imagen: "./multimedia/aurisazul.webp" },

    { nombre: "Auriculares inalambricosS Tune 510BT",
     color: "Blanco", 
     precio: "9000", 
     stock: "1", 
     id: 5, 
     marca: "JBL",
     imagen: "./multimedia/aurisjbl.webp" },

    { nombre: "Auriculares in-ear inalambricos Buds PRO", 
    color: "Blanco",
    precio: "9800", 
    stock: "1", 
    id: 6,
     marca: "XIAOMI",
     imagen: "./multimedia/aurisplata.webp"},

    { nombre: "Auriculares in-ear inalambricos GAMER GT",
     color: "Negro",
     precio: "7000", 
     stock: "1",
      id: 7, 
      marca: "HAYLOU",
     imagen:"./multimedia/aurishaylou.webp" },

    { nombre: "Auriculares in-ear inalambricos Xiaomi Redmi Buds ",
     color: "Blanco", 
     precio: "9000",
      stock: "1", 
      id: 8, 
      marca: "XIAOMI",
      imagen:"./multimedia/aurisxiaomi.webp" },

    { nombre: "Auriculares Bluetooth M10", 
    color: "Negro", 
    precio: "3100", 
    stock: "1", 
    id: 9, 
    marca: "HIFISOUND", 
    imagen:"./multimedia/auricularesbluetooth.webp" },

    { nombre: "Auriculares in ear Sony WF-C500", 
    color: "Negro", 
    precio: "17900", 
    stock: "1", 
    id: 10, 
    marca: "SONY", 
    imagen:"./multimedia/aurissony.webp" },

    { nombre: "Auriculares in-ear unnic beans", 
    color: "Negro",
     precio: "6300", 
     stock: "1", 
     id: 11, 
     marca: "UNNIC", 
     imagen:"./multimedia/aurisunic.webp" },

    { nombre: "Auriculares Soundcore Life", 
    color: "Rosa",
     precio: "79000", 
     stock: "1", 
     id: 12, 
     marca: "SOUNDCORE", 
     imagen:"./multimedia/aurisrosa.webp" },

    { nombre: "Auriculares BEHRINGERH HM1000", 
    color: "Gris y Negro", 
    precio: "9000", 
    stock: "1", 
    id: 13, 
    marca: "BEHRINGERH", 
    imagen:"./multimedia/aurisbehringer.webp" },

    { nombre: "Auriculares Logitech H390", 
    color: "Negro",
     precio: "10000", 
     stock: "1", 
     id: 14, 
     marca: "LOGITECH", 
     imagen:"./multimedia/aurislogitech.webp" },

    { nombre: "Auriculares in-ear 2 Basic",
     color: "Blanco", 
     precio: "6900", 
     stock: "1", 
     id: 15, 
     marca: "XIAOMI", 
     imagen:"./multimedia/aurispalito.webp" },

    { nombre: "Auriculares JBL WAVE 300TWS", 
    color: "Negro", 
    precio: "25000", 
    stock: "1", 
    id: 16, 
    marca: "JBL", 
    imagen:"./multimedia/aurisjblpalito.webp" },

    { nombre: "Auriculares Aiwa BT301", 
    color: "Blanco", 
    precio: "8000", 
    stock: "1", 
    id: 17, 
    marca: "AIWA", 
    imagen:"./multimedia/aurisaiwa.webp" },

    { nombre: "Auriculares inalambricos Lenovo",
     color: "Negro", 
     precio: "7400", 
     stock: "1", 
     id: 17, 
     marca: "LENOVO", 
     imagen:"./multimedia/aurislenovo.webp" },

    { nombre: "Auriculares Gamer T-DAGGER con luz", 
    color: "Negro",
     precio: "6900", 
     stock: "1", 
     id: 18, 
     marca: "TDAGGER", 
     imagen:"./multimedia/aurisdagger.webp" },
    { nombre: "Auriculares Soundcore Life Series", 
    color: "Negro", 
    precio: "17900",
    stock: "1", 
    id: 19, 
    marca: "SOUNDCORE", 
    imagen:"./multimedia/aurissound.webp" },

]
